services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
    networks:
      - network
    env_file:
      - .env
  tasks-service:
    build: ./tasks-service
    networks:
      - network
    env_file:
      - .env
  groups-service:
    build: ./groups-service
    networks:
      - network
    env_file:
      - .env
  authorization-server:
    build: ./authorization
    ports:
      - "9000:8080"
    networks:
      - network
    env_file:
      - .env
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    networks:
      - network
    env_file:
      - .env

networks:
  network:
    driver: bridge